### PR TITLE
Fix snap packaging

### PR DESCRIPTION
**Pull request by ppd**
- simplify snapcraft.yaml
- use source from current directory
- Use kde-neon extension instead of shipping QT (implies core18)
- use app name with dashes so it does not get prefixed
- add gitignore for snap packages

### CODE REVIEW

**Comment by kebekus** [comment]
Thank you!

**Comment by kebekus** [comment]
Thank you for you help! I have tried your suggested improvement, but now compilations fails. Any suggestion would be extremely helpful!

```
CMake Error at /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:27 (message):
  The imported target "Qt5::Gui" references the file

     "/usr/lib/x86_64-linux-gnu/libEGL.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:63 (_qt5_Gui_check_file_exists)
  /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:85 (_qt5gui_find_extra_libs)
  /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5GuiConfig.cmake:186 (include)
  /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5Quick/Qt5QuickConfig.cmake:101 (find_package)
  /snap/kde-frameworks-5-core18-sdk/current/usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:21 (find_package)
```

**Comment by ppd** [comment]
I'll take a look. Sorry for the inconvenience; I think my build environment wasn't quite clean, and so I didn't catch that.

**Comment by ppd** [comment]
See https://github.com/Akaflieg-Freiburg/addhoursandminutes/pull/3

**Pull request merged**
